# The http configuration part for integration with other system
retrofit:
  log:
    enabled: true
    content: BASIC # NONE, BASIC, HEADERS, BODY
    level: INFO

  connection:
    retryTimes: 5
    connectTimeout: 5000 # The timeout for http request, mile seconds, so 5000 means 5 seconds
    maxIdleConnections: 5 # The maximum number of idle connections for each address.
    keepAliveDuration: 5 # The time (minutes) to live for each idle connections.

  # identity: current available
  # baseUrl: the base part of business system url, would be changed by nginx location, "/" is not required to be the end of url
  endpoints:
    - identity: default
      baseUrl: http://127.0.0.1:${random.int(10000,15000)}
    - identity: ai
      baseUrl: http://127.0.0.1:${random.int(10000,15000)}
    - identity: mi
      baseUrl: http://127.0.0.1:${random.int(10000,15000)}
    - identity: cep
      baseUrl: http://127.0.0.1:${random.int(10000,15000)}
